export const SET_PAGE = 'SET_PAGE'

export const HOTEL_LOAD = 'HOTEL_LOAD'
export const HOTEL_SUCCESS_LOADED = 'HOTEL_SUCCESS_LOADED'
export const HOTEL_FAIL_LOADED = 'HOTEL_FAIL_LOADED'
export const DELETE_HOTEL = 'DELETE_HOTEL'

export const HOTEL_LIST_LOAD = 'HOTEL_LIST_LOAD'
export const HOTEL_LIST_SUCCESS_LOADED = 'HOTEL_LIST_SUCCESS_LOADED'
export const HOTEL_LIST_FAIL_LOADED = 'HOTEL_LIST_FAIL_LOADED'

export const COUPON_LOAD = 'COUPON_LOAD'
export const COUPON_SUCCESS_LOADED = 'COUPON_SUCCESS_LOADED'
export const COUPON_FAIL_LOADED = 'COUPON_FAIL_LOADED'
export const DELETE_COUPON = 'DELETE_COUPON'

export const RESERVATION_LOAD = 'RESERVATION_LOAD'
export const RESERVATION_SUCCESS_LOADED = 'RESERVATION_SUCCESS_LOADED'
export const RESERVATION_FAIL_LOADED = 'RESERVATION_FAIL_LOADED'
export const RESERVATION_SUCCESS_DELETED = 'RESERVATION_SUCCESS_DELETED'
export const UPDATE_RESERVATION = 'UPDATE_RESERVATION'
export const DELETE_RESERVATION = 'DELETE_RESERVATION'
